### ISSUE TITLE
Laravel 5 throwing an error

### ISSUE THREAD

**Issue by alexleonard** [cviebrock/image-validator#11]
I'm guessing this package hasn't been setup for Laravel 5, but thought I'd let you know that if I try to use it I get an error:

    Exception in Store.php line 236:
    Serialization of 'Symfony\Component\HttpFoundation\File\UploadedFile' is not allowed

If I don't use any image-validator rules, say just use `'photo' => 'required|image',` then the validation works and I can move on to the next step.

Anyone have any luck getting this working in L5?

**Comment by alexleonard** [comment]
Now that L5 has been released, is there any plan to update this package for it?

Would be awesome!

Thanks

**Comment by Djuki** [comment]
As I see the package is ready for L5 but it is not tagged and updated on composer. When we can expect this?

**Comment by cviebrock** [comment]
D'oh!  Doing it now.

**Comment by cviebrock** [comment]
Tag `2.0.0-alpha` pushed to packagist.org ... let me know how it goes!

**Comment by Djuki** [comment]
@cviebrock Thanks. I tested alpha and it works fine so far.
