### ISSUE TITLE
validation of image URL

### ISSUE THREAD

**Issue by johannes-z** [cviebrock/image-validator#23]
Is it possible to use this, or change it, to allow the validation of linked images? The stock laravel validations only work if you upload an image to the server, but obviously don't work, if you add an image via an URL.

**Comment by cviebrock** [comment]
I don't think I'd add this.  I don't think a validation class should be responsible for loading external documents (in this case, it would have to download the image).

A better solution would be to download the image pre-validation, and pass it into the Validator as a `Symfony\Component\HttpFoundation\File\File`, which should work.
