### ISSUE TITLE
GD-ext required?

### ISSUE THREAD

**Issue by willwashburn** [cviebrock/image-validator#26]
Thanks for this library, pretty sweet. 

I poked around a bit and couldn't find why the GD extension was required. Is there a reason?

Can this be safely removed or is there something I'm missing?

Thanks in advance!

**Comment by cviebrock** [comment]
Good point! I guess I forgot that `getimagesize` doesn't require GD.

Feel free to submit an MR fixing this, or I'll take care of it when I'm back from vacation.
