### ISSUE TITLE
"PHP function nesting level of '5000' has been reached", if there's another extended validation

### ISSUE THREAD

**Issue by Ardakilic** [cviebrock/image-validator#3]
Hey again,

I have found a new error on my end, I hope you can help me:

When I add another extended validation from another place, I get an error like this if ```image_size``` rule is run from validation:

```
Symfony \ Component \ Debug \ Exception \ FatalErrorException
Aborting! The New Relic imposed maximum PHP function nesting level of '5000' has been reached. This limit is to prevent the PHP execution from catastrophically running out of C-stack frames. If you think this limit is too small, adjust the value of the setting newrelic.special.max_nesting_level in the newrelic.ini file, and restart php. Please file a ticket at https://support.newrelic.com if you need further assistance.
```

This is my extension of Laravel Validation Class: [http://laravel.io/bin/MN8l](http://laravel.io/bin/MN8l)

To enable this, I've added this line in my ```index.php``` before ```$app->run();```:

```require_once __DIR__.'/app/lib/Validation.php';```

The error occurs on the method ```__call()``` on my ```app/lib/validation.php``` as Whoops says.

What could be the issue, is there any way to resolve this?

Thanks in advance,

**Comment by cviebrock** [comment]
Stale issue.  The L5 version is in development now, but let me know if you still have trouble with the `1.x` branch and Laravel 4.2.

**Comment by Quagh** [comment]
This issue is about multiple extended validators, right? Don't seem to have an issue with it. Extending the default validator with my own in a service provider, and then it runs your service provider to extend it even further. All my custom validation rules seem to work fine (on first sight).
