### ISSUE TITLE
Script Error on missing locale

### ISSUE THREAD

**Issue by superdummy** [cviebrock/image-validator#30]
Hi, 

thanks for your cool laravel projects, i use 3 of them and they are great!

I stumbled on the problem that I configured two locales, that are not yet translated (like es and cn). Then the image validator kills the whole laravel app when registering the ImageValidationServiceProvider as a string is tried to be accessed as array

The problem lies in this line: 
	`$translation = trans('image-validator::validation');`
		`$this->app['validator']->extend($rule, 'Cviebrock\ImageValidator\ImageValidator@validate' . $method, $translation[$rule]);`

=>The variable `$translattion` is then not an array (if no translations are found) but actually a string (as laravel will return the key in case no translation is present) and then trying to access $rule in the array results in a hard error. 

But its very easy to fix for example like this (generating the rule via appending the $rule to the key to be looked up):
`$translation = trans('image-validator::validation.'.$rule);`
		`$this->app['validator']->extend($rule, 'Cviebrock\ImageValidator\ImageValidator@validate' . $method, $translation);`

Thanks!

**Comment by cviebrock** [comment]
Thanks!
