### ISSUE TITLE
Support for irrational numbers

### ISSUE THREAD

**Issue by rephiscorth** [cviebrock/image-validator#31]
I was trying an aspect ratio of `3,2`, with an image of `1024x682` and another of `1024x683` but it didn't pass. I'm guessing it's because the correct height would be `862.66666666....`. Can we have support for this? Maybe like flooring or ceiling the result could work. Thanks in advance!

**Comment by cviebrock** [comment]
Sorry for the long delay.

Yeah, this isn't ideal.  Right now we convert the aspect to a fraction (i.e. 3/2 = 1.5) and then compare that with the image width/height to 10 decimal places.  So your images are either 1.5014662757 or 1.4992679356.

Reducing the check down to 1 or 3 decimal places doesn't seem like a great solution.  But perhaps I could check that `round(image width / aspect) = image height` instead.

**Comment by cviebrock** [comment]
Can you try `dev-master`? I refactored the aspect checking to accommodate this issue.

**Comment by cviebrock** [comment]
Actually, I've now published version 2.1.0 which should have this issue fixed.  Thanks!
