### ISSUE TITLE
Support ">" in image_aspect

### ISSUE THREAD

**Issue by johnlui** [cviebrock/image-validator#33]
`/vendor/cviebrock/image-validator/src/ImageValidator.php` line 118:
```php
// JohnLui 2015-11-12 15:33:43
// support ">" in image_aspect
if (substr($parameters[0],0,1)=='>') {
	if ( bccomp(substr($parameters[0], 1), $image_aspect, 10) == -1 ) {
		return true;
	}
}
```

**Comment by johnlui** [comment]
support "<":

```php
if (substr($parameters[0],0,1)=='<') {
	if ( bccomp(substr($parameters[0], 1), $image_aspect, 10) == 1 ) {
		return true;
	}
}
```

**Comment by cviebrock** [comment]
Can you make a PR with those? Add some tests and update the readme with how one would use them, and I'll merge it in.

Thanks!

**Comment by johnlui** [comment]
Thanks for your awesome project!

I will do it when I have the time.

From My iPhone

**Comment by cviebrock** [comment]
I guess you haven't had the time. 😞   Re-open or submit a PR when you can.
