### ISSUE TITLE
Support laravel 5.1

### ISSUE THREAD

**Issue by DJZT** [cviebrock/image-validator#35]
laravel 5.1 not supports. Please check

BadMethodCallException in Validator.php line 2676:
Method [validateImageSize] does not exist.

**Comment by Krato** [comment]
Same to me. Some fix?

**Comment by dhimanmohit2548** [comment]
Please add the service provider to your config/app.php file

Cviebrock\ImageValidator\ImageValidatorServiceProvider::class

Then enjoy!

**Comment by DJZT** [comment]
@dhimanmohit2548 Service provider is added.
command php artisan (clear-compiled / cache-clear / optimize) commands did not help

**Comment by cviebrock** [comment]
Closed for lack of response. No one else has reported this, so I suspect something else is going on in your install.

If you can provide more details on the error, then feel free to reopen the issue.

**Comment by webcrazy** [comment]
~~~
BadMethodCallException in Validator.php line 3020:
Method [validateImageSize] does not exist.
~~~
I have the same issue. Laravel 5.2
