### ISSUE TITLE
Support custom validation message for greaterxxxx, ...

### ISSUE THREAD

**Issue by libern** [cviebrock/image-validator#38]
Currently, I can't find any way that can add validation messsage for, e.g: greaterthanorequal in the locale that is not available.

Guide me someway to do that, please.

The result currently in chinese is like:
Image 的尺寸要宽greater than or equal to 600 pixels和高greater than or equal to 600 pixels 

I find no way to change 
	'greaterthanorequal' => 'greater than or equal to :size pixels',
this part because it has a namespace.

**Comment by libern** [comment]
cviebrock

**Comment by libern** [comment]
@cviebrock

**Comment by cviebrock** [comment]
Not sure ... but feel free to submit a PR with translations for Chinese!

**Comment by cviebrock** [comment]
Closed for lack of response. 😞
