### ISSUE TITLE
Validation Message for Aspect Ratio Validation

### ISSUE THREAD

**Issue by ShirajG** [cviebrock/image-validator#41]
The validation message for the aspect ratio only lists the first value in the error message.
ie: an aspect ratio of 8,5 results in a validation message that reads: `The image-{image name} aspect ratio must be 8.`

**Comment by cviebrock** [comment]
Can you try `dev-master` and let me know if that fixes it for you?

**Comment by cviebrock** [comment]
Actually, I've now published version 2.1.0 which should have this issue fixed.  Thanks!
