### ISSUE TITLE
Issue with laravel 5.2

### ISSUE THREAD

**Issue by webcrazy** [cviebrock/image-validator#43]
Hello @cviebrock

Please check with laravel version 5.2

I got this error within form request when I try to upload.
```
BadMethodCallException in Validator.php line 3255:
Method [validateImageSize] does not exist.
```

Thanks

**Comment by cviebrock** [comment]
Did you load the package's service provider?

**Comment by webcrazy** [comment]
Yes sure. I followed the documentation.

**Comment by burninghugo** [comment]
I realize this issue is almost a month old, but I can confirm this is working in 5.2.

Not sure if it matters, but they changed the way you add service providers in 5.2: `Cviebrock\ImageValidator\ImageValidatorServiceProvider::class`
