### ISSUE TITLE
Lumen support

### ISSUE THREAD

**Issue by WrongWay** [cviebrock/image-validator#44]
Seems that there is a problem with this package in Lumen. It relies on `trans()` function, that is only present in Laravel, but not in Lumen (although it has a dependency on illuminate/translate)

**Comment by cviebrock** [comment]
Can you try `dev-master` and let me know if the fix I just pushed actually works?

**Comment by WrongWay** [comment]
Nope, still getting
```
Fatal error: Call to undefined function Cviebrock\ImageValidator\trans() in D:\Work\Server\domains\artapi.dev\vendor\cviebrock\image-validator\src\ImageValidatorServiceProvider.php on line 78
```

**Comment by cviebrock** [comment]
You changed that line to:

```
$translation = $this->app['translator']->trans('image-validator::validation');
```

I assume?

**Comment by WrongWay** [comment]
Yeah, exactly.

**Comment by cviebrock** [comment]
Pushed ... I'll tag 2.1.0 shortly.  Thanks!

**Comment by WrongWay** [comment]
Thanks to you :)
