### ISSUE TITLE
Argument 4 passed to Cviebrock\ImageValidator\ImageValidator::__construct() must be of the type array

### ISSUE THREAD

**Issue by nWidart** [cviebrock/image-validator#45]
Hello,

I've been getting this error since a recent update.

``` php
Type error: Argument 4 passed to Cviebrock\ImageValidator\ImageValidator::__construct() must be of the type array, string given, called in /home/vagrant/monitoring-assistance/vendor/cviebrock/image-validator/src/ImageValidatorServiceProvider.php on line 34
```

This error is fixed by not type hinting for an array as the forth argument. This issue from what I could debug is that the translations aren't loaded, and thus the key is sent to the constructor.

**Comment by nWidart** [comment]
Update:

When running `dd(trans('image-validator::validation'));` in the `ImageValidatorServiceProvider` right before the `this->app->bind`, it finds the validation keys (array).

However, when running the same dd() function inside the bind closure, it doesn't find the validation keys.

**Comment by DaniloPolani** [comment]
For me this is not solving the problem. I use the version 2.4 with L5.1 and the `dd()` of `trans('image-validator::validation')` outside the app bind returns a string.
