### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by RalphMRivera** [cviebrock/image-validator#53]
I can't require the image validator into Laravel 5.4.

I get the following error:

local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Cviebrock\ImageValidator\ImageValidator::__construct() must be an instance of Symfony\Component\Translation\TranslatorInterface, instance of Illuminate\Translation\Translator given, called in /vendor/cviebrock/image-validator/src/ImageValidatorServiceProvider.php on line 35 in /vendor/cviebrock/image-validator/src/ImageValidator.php:15

**Comment by libern** [comment]
+1

**Comment by cviebrock** [comment]
Can you try the `dev-master` version and let me know if that works?  If so, I'll release version 2.2 which should support Laravel 5.4.

**Comment by libern** [comment]
@cviebrock Well done. Tested. It works and can be installed for 5.4.

**Comment by cviebrock** [comment]
Thanks @libern.

Anybody else -- @RalphMRivera , @jeanquark -- want to weigh in as well?

**Comment by jvrhenen** [comment]
Works for Laraval 5.4

**Comment by libern** [comment]
@cviebrock Could you release?

**Comment by cviebrock** [comment]
Done!
