### ISSUE TITLE
How to show the language based dynamic error message?

### ISSUE THREAD

**Issue by ssboopathi1991** [cviebrock/image-validator#57]
My image width and heights are dynamic. We are using two types of language. How to show the language based dynamic error message?

Example:
`$rules = [`
       `'category_image' => 'image_size:250,300',//250 and 300 are dynamic value.`
    `];`

**Comment by cviebrock** [comment]
What error message do you get?  No matter what values you pass in the rule, your error output should be:

```
The category image must be 250 pixels wide and 300 pixels tall.
```

... and `250` and `300` being replaced with what ever dynamic values you pass.
